pik-piam/modelstats

.buildlibrary, .zenodo.json, DESCRIPTION, R/loopRuns.R, README.md
reduce column size for `-t` and all other cases where longer paths are provided.
=> fix column size for -t

.Rbuildignore, .buildlibrary, .pre-commit-config.yaml, .zenodo.json, DESCRIPTION, Makefile, R/loopRuns.R, README.md
- nchar(".") = 1 is too short :)
=> do not get very short column if mydir=.

.buildlibrary, .zenodo.json, DESCRIPTION, R/modeltests.R, README.md
Actually using relative paths correctly.
=> Bugfix: path to teststatus

.buildlibrary, .github/workflows/check.yaml, .zenodo.json, DESCRIPTION, R/modeltests.R, README.md, man/modeltests.Rd
Forgot buildLibrary in https://github.com/pik-piam/modelstats/pull/31
=> buildLibrary()

.buildlibrary, CITATION.cff, DESCRIPTION, R/foundInSlurm.R, R/loopRuns.R, README.md
- instead, write user who is running the run into the `inSlurm` column
- top: old; bottom: new
=> don't show 'run interrupted' if run by other user

.buildlibrary, CITATION.cff, DESCRIPTION, R/foundInSlurm.R, README.md
in PR #34 I accidentally dropped the run name which was necessary for REMIND-MAgPIE runs to correctly identify the slurm status
=> bugfix inSlurm message rs2 for coupled runs

.buildlibrary, CITATION.cff, DESCRIPTION, R/foundInSlurm.R, README.md
- slurm for coupled runs was not correctly derived
=> bugfix rs2 coupled runs

.buildlibrary, CITATION.cff, DESCRIPTION, R/colRunType.R, R/foundInSlurm.R, R/getRunStatus.R, R/loopRuns.R, R/printOutput.R, R/promptAndRun.R, README.md
- see individual comments below
- you can test by running `rs3` instead of `rs2`
=> run, rs2, run. (faster, fix error, add features)

.buildlibrary, CITATION.cff, DESCRIPTION, R/foundInSlurm.R, README.md
- were sometimes confused with `startup`
=> fix small bug to show pending runs correctly

.buildlibrary, .pre-commit-config.yaml, CITATION.cff, DESCRIPTION, R/loopRuns.R, R/promptAndRun.R, README.md
- kick out empty directories from -f mode 
- if in REMIND folder, show runs from `output` subfolder
=> kick out empty directories from -f mode

.buildlibrary, CITATION.cff, DESCRIPTION, R/foundInSlurm.R, R/getRunStatus.R, README.md
- if run is interrupted, look into log and see what caused the error
- if more than one user is running the same job (sign of something fishy), state it
- identify all calibration jobs
- some lintr stuff
=> differentiate timeout & memory interrupt, lintr

.buildlibrary, CITATION.cff, DESCRIPTION, R/promptAndRun.R, README.md, man/promptAndRun.Rd
Run `rs2 -t SSP2EU-Base` or something like that to show only those that match the pattern.
=> allow to filter AMT runs

.buildlibrary, CITATION.cff, DESCRIPTION, R/modeltests.R, README.md
modeltests was checking for inAppResults to be "TRUE" (https://github.com/pik-piam/modelstats/blob/efed27b02054a4175abaeb19adc64ffa127e6cb0/R/modeltests.R#L279), but it is either "no" or "yes" (https://github.com/pik-piam/modelstats/blob/master/R/getRunStatus.R#L115). That's is most likely why we got "Some run(s) did not report correctly" although all runs reported fine according to the table: https://gitlab.pik-potsdam.de/landuse/testing_suite
=> bugfix TRUE -> yes

.buildlibrary, CITATION.cff, DESCRIPTION, R/foundInSlurm.R, README.md
=> fix that -mag-1 runs are stated as running if -mag-10 is running

.buildlibrary, CITATION.cff, DESCRIPTION, R/promptAndRun.R, README.md
- to allow choosing a specific order, or just have them sorted alphabetically
=> rs2: don't sort user-selected dirs by time

.buildlibrary, CITATION.cff, DESCRIPTION, R/modeltests.R, README.md
This is an amendment to https://github.com/pik-piam/modelstats/pull/92 and addresses @orichters comments. 
Closes #82
=> Add testthat result to bot message. Keep testthat log file longterm in tests folder.

.buildlibrary, CITATION.cff, DESCRIPTION, R/getRunStatus.R, README.md
would have helped me to understand the confusion today more quickly, see https://mattermost.pik-potsdam.de/rd3/channels/remind-magpie-coupling
=>  state as RunStatus if waiting for REMIND/MAgPIE lock 

.buildlibrary, .github/workflows/check.yaml, .pre-commit-config.yaml, CITATION.cff, DESCRIPTION, R/modeltests.R, README.md
Bugfix: move definition of variable outside the if-clause in order to also define variable for runs that did not converge
=> Bugfix: move definition of variable outside the if-clause

.buildlibrary, CITATION.cff, DESCRIPTION, R/getRunStatus.R, README.md
which is the other standard place, see https://github.com/remindmodel/remind/blob/5f7dbdf4cb1f782f58ff195971be3652fc0307f9/start_bundle_coupled.R#L55
=> find MAgPIE logs also if folder is ../magpie/

.buildlibrary, CITATION.cff, DESCRIPTION, R/loopRuns.R, README.md
- partially undo https://github.com/pik-piam/modelstats/pull/51
- folders only containing log.txt should not be skipped
=> don't skip folders containing log.txt

.buildlibrary, CITATION.cff, DESCRIPTION, R/getRunStatus.R, R/loopRuns.R, README.md
- the grep command only worked if the folder did not contain a blank
=> add orange 'no mif', don't fail on run folder with blanks

.buildlibrary, CITATION.cff, DESCRIPTION, R/loopRuns.R, R/modeltests.R, README.md
adapt to what is used in remind2: https://github.com/pik-piam/remind2/blob/master/tests/testthat/test-convGDX2mif.R#L18
=> switch upload to rse folder to NPi

.buildlibrary, CITATION.cff, DESCRIPTION, R/modeltests.R, README.md
The core change of #133 got lost somehow, this PR now adds it.
=> amend: data changelog print RAW luc emis variable
