- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/promptAndRun.R
- README.md
I still get a bit lost in the number of old, finished runs, and therefore propose a new `-a` switch, showing only active runs. Also, sort the runs, and also cover coupled runs in parallel mode.
If that is merged, the help of `rs2` has to be extended, I guess.
> add -a mode with only active runs, sort runs

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/getRunStatus.R
- README.md
if a job is not completed and still `Run in progress`, add the time difference between the preparation and now, together with a `>` sign:
```
C_d_delfrag_bIT-rem-1  8.8 hours    TRUE     nash         Normal completion   100/100           not_converged          2                    TRUE      TRUE
C_d_delfrag_bIT-rem-2  > 2.8 hours  TRUE     nash         Run in progress     35/100            222272222222           NA                   NA        FALSE
C_o_1p5c_bIT-rem-1     15.6 hours   TRUE     nash         Normal completion   100/100           not_converged          2                    TRUE      TRUE
C_o_1p5c_bIT-rem-2     > 6.9 hours  TRUE     nash         Run in progress     49/100            222222222222           NA                   NA        FALSE
```
> add runtime for non-completed jobs

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/getRunStatus.R
- README.md
If `runstatistics.rda` exists, but doesn't contain modelstat because not is still running, take it from `fulldata.gdx`
> show modelstat also during run

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/modeltests.R
- R/printOutput.R
- README.md
fixing the broken layout of the AMT mail
I could only partly test it, but I took the respective lines from the write command and used `message` to print them, and everything aligned well.
> adapt modeltests.R to shorter run reporting

- .buildlibrary
- .pre-commit-config.yaml
- .zenodo.json
- DESCRIPTION
- R/getRunStatus.R
- README.md
When a run is aborted, `modelstat` has a `numeric(0)` value in the `runstatistics.rda` file, which was causing a bug in the reading of `modelstat` of `rs2`
> Bugfix reading modelstat for aborted runs

- .buildlibrary
- .github/workflows/lucode2-check.yaml
- .zenodo.json
- DESCRIPTION
- README.md
- man/modelstats-package.Rd
I accidentally pushed the code change directly to pik-piam/modelstats thus this PR contains only the version increment
> version bump for renv in modeltests update

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/modeltests.R
- R/promptAndRun.R
- README.md
If I'm in an output subdirectory and run `rs2`, I get:
```
Please choose folders:
1: all
2: ./EDGE-T
3: ./magicc
4: ./renv
5: Search by pattern...
```
Nonsense :)
After this PR, if `rs2` is started with no further qualifiers and `full.gms`, `log.txt`, `config.Rdata`, `prepare_and_run.R` exist in the current folder, it assumes this is a run folder and shows the result of this run. And in the selection process, you can now not only select the subfolders, but also the current folder itself (`.`).
> if rs2 is run in output subdirectory, show results of this run

- .buildlibrary
- .github/workflows/lucode2-check.yaml
- .zenodo.json
- DESCRIPTION
- R/modeltests.R
- README.md
- man/modeltests.Rd
I tried to understand the AMT code, in the process I refactored much of it. It now has considerably fewer linter warnings, too.
Also, I added a sleep into a busy wait to not 100% one core of the login node unnecessarily in magpie tests.
I can't really test the changes anywhere, so I guess I'll just put them into production?
> Refactor AMT

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/foundInSlurm.R
- R/loopRuns.R
- README.md
- man/foundInSlurm.Rd
- show `PD` in column `inSlurm` if run has not started yet together with a shortcut of the `qos` used.
looks like this:
``` bash
h_ndc_EUR_import_tax_050_2023-03-08_17.39.54       > 37.9 mins  TRUE     nash         Run in progress     1/100             NA                     NA                   NA        FALSE
h_ndc_EUR_import_tax_100_2023-03-08_17.40.19       > 58.2 mins  TRUE     nash         Run in progress     2/100             NA                     2: Locally Optimal   NA        FALSE
h_ndc_EUR_import_tax_100_oil_2023-03-08_17.40.56   NA           PD shor  nash         full.log missing    NA                NA                     NA                   NA        NA
h_ndc_EUR_import_tax_200_2023-03-08_17.40.37       NA           PD shor  nash         full.log missing    NA …
```
> show PENDING in column inSlurm if run has not started yet

- R/modeltests.R
Hi,
Use the `AMT` group in `config/scenario_config.csv` instead of `config/scenario_config_AMT.csv` in AMT runs.
Cheers
Mika
> Use default scenario config in AMT runs

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/modeltests.R
- README.md
- Bugfix: use `withr::with_dir("output",...` instead of `setwd("output)` to ensure the correct path after the execution of `evaluateRuns()`
- move file `.testsstatus` from model folders (remind or magpie) to the respective parent folder, from where the modeltest are actually started and where also the logfiles are written.
- move code chunk that retrieves `paths` down to where `paths` is actually used.
- add hours and seconds to the timestamp in some log messages
> Bugfix regarding the working directory

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/foundInSlurm.R
- R/getRunStatus.R
- R/loopRuns.R
- R/modeltests.R
- R/promptAndRun.R
- README.md
- if you run rs2 in magpie folder, try to find the corresponding REMIND slurm job
- for MAgPIE, show convergence progress during run instead of `NA`
- show when REMIND runs reporting
- increase space in title col for AMT to avoid directory names being cut
- add `-p` = piam mode that shows all coupled REMIND runs + MAgPIE runs from magpie/output subfolder
> improve logging of coupled runs, increase space in title col for AMT

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/modeltests.R
- README.md
- There was still one character missing to show the AMT folder names completely
- Instead, reduce size of mif and AppResults column. The scenario rows of AppResults will just be one letter, but I think y or n should be self-explanatory
- Please review carefully, as I could not test it properly
> adjust column width for AMTs

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/foundInSlurm.R
- R/promptAndRun.R
- README.md
For coupled and standalone runs, this is the output of `/p/system/slurm/bin/squeue -h -o '%u %Z %j %M %T %q'`:
```
username /p/tmp/remind/ C_d_strain_d95high-rem-10 17:39:49 RUNNING priority
username /p/tmp/remind/output/h_cpol_2023-07-18_11.37.03 h_cpol 4:47 RUNNING priority
```
So I simply check for an additional blank after the runname to make sure it works. Notice that [this line](https://github.com/pik-piam/modelstats/blob/master/R/foundInSlurm.R#L22) matches the third part (C_d_strain_d95high-rem-10) for coupled runs, while for standalone, it matches the folder.
> fix that -rem-1 runs are stated as running if -rem-10 is running

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/modeltests.R
- README.md
- After renaming `testOneRegi` to `1Regi EUR`, the check was not adapted, yet, leading to a false positive for testOneRegi not converging [here](https://gitlab.pik-potsdam.de/REMIND/testing_suite/-/commit/a197a2f6c2d17fc6e477cc79c0e519801db18f5e).
> for modeltests, identify correctly whether testOneRegi failed

- .buildlibrary
- .github/workflows/check.yaml
- .pre-commit-config.yaml
- CITATION.cff
- DESCRIPTION
- R/getRunStatus.R
- README.md
- if a run is restarted or an additional MAgPIE-coupling iteration is started but that slurm task is still pending, `rs2` stated the Runtime of the earlier run. Now, it states that the task is pending, which I think is more valuable to the user.
- Still, `RunStatus` is something like `Normal completion` or so, so the user can identify that this was a restart or something like that.
> always state if run is pending

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/modeltests.R
- README.md
`default-AMT-` [is stated not to have converged](https://gitlab.pik-potsdam.de/REMIND/testing_suite/-/commit/89bc5b6e9a589440c4331d50e535aa0611385365#8ec9a00bfd09b3190ac6b22251dbb1aa95a0579d_51_57), while in fact it is just called `default-AMT`. Fixing that.
> correctly identify whether default scenario converged

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/modeltests.R
- README.md
- [printing it in seconds here is not a good idea, I think](https://gitlab.pik-potsdam.de/REMIND/testing_suite/-/commit/89bc5b6e9a589440c4331d50e535aa0611385365#8ec9a00bfd09b3190ac6b22251dbb1aa95a0579d_51_57)
- was caused by #66
> also print human-readable Runtime in modeltests

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/foundInSlurm.R
- R/promptAndRun.R
- README.md
- if you changed the prefix from `C_` to something else, the slurm job was not found anymore
- `rs2 -s` now also shows non-coupled runs, but only the most recent
> expand short mode (-s) to non-coupled, fix search for coupled

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/modeltests.R
- README.md
- was surprised where [the "Some run(s) did not converge" complaint](https://gitlab.pik-potsdam.de/REMIND/testing_suite/-/blob/14aad5ea5330cf33dcff6c3e3816653d61400657/README.md) came from
- well, `not converged` should be if the RunStatus is *not* `converged`
- match `testOneRegi` on Runtype, not directory name (was not the problem, but is better anyway, I think)
> fix AMT 'did runs converge' message

- .buildlibrary
- .github/workflows/check.yaml
- CITATION.cff
- DESCRIPTION
- R/getRunStatus.R
- R/promptAndRun.R
- README.md
- since a while, calibrations show no `Clb_converged` anymore, but just `converged`. This [misleads AMT runs](https://gitlab.pik-potsdam.de/REMIND/testing_suite/-/commit/7fe464aa5d137328f3105633a77859bc4f4bf1da) into thinking some run did not converge
- Did we have `input_02.gdx` etc. until ~ September 2022? The amount of `input_xx.gdx` files was used to determine whether a converged iteration was a successful calibration. Now, look for the corresponding `fulldata_xx.gdx` which did not seem to exist earlier.
- fix a small bug if you manually pass a folder that contains a `b` `(with `rs2 SSP2-base`), that was sometimes removed.
> fix Clb_converged, don't remove 'b' from folder names

- .buildlibrary
- .github/workflows/check.yaml
- CITATION.cff
- DESCRIPTION
- R/modeltests.R
- README.md
Together with the REMIND AMTs execute  `make test-full-slurm` and evaluate the result and append it to the mattermost bot message.
> For REMIND AMTs: execute `make test-full-slurm`

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/getRunStatus.R
- R/loopRuns.R
- R/modeltests.R
- README.md
For REMIND model: if a `REMIND_generic<scenname>_summation_errors.csv` exists in the individual run folder, report `sumErr` in the `Mif` column of `getRunStatus`. This will be displayed also in `rs2` and added to the summary message of the AMTs.
```
Folder                                            Runtime      inSlurm   RunType      RunStatus          Iter              Conv                   modelstat              Mif     AppResults 
default-AMT_2024-03-01_22.08.46                   NA           no        nash         Abort 12R*5*Infes  5/100             566555550555           6: Intermed Infes      no      no
SDP_MC-NDC-AMT_2024-03-02_06.06.48                NA           no        nash         Abort 10R*5*Infes  5/100             000500000050           5: Locally Infes       no      no …
```
> REMIND: Check for summation errors and report in already existing `Mif` column of `getRunStatus`

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/colRunType.R
- R/modeltests.R
- README.md
Also: Update check for debug run (cfg$gms$cm_nash_mode is no string anymore but a number)
> Use the fulldata.gdx of a successful SSP2EU-NPi-AMT to update the gdx on the RSE server

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/modeltests.R
- README.md
Start `testOneRegi-AMT` as first AMT run (before starting AMTs from scenario_config.csv to also trigger the input data download) instead of starting `default-AMT`. The latter will be started as part of the full REMIND model tests (test_05-default.R). So far it was started twice. The first one (`testOneRegi-AMT`) was removed from the list of AMT runs in the scenario_config.csv so it will be started only once.
> Dont start `default-AMT` twice

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/foundInSlurm.R
- README.md
- make sure other prefixes work as well
- should be sufficient to identify a magpie run by `-mag-1` etc. at the end
- FYI @dklein-pik
> remove hardcoded C_ prefix of REMIND-MAgPIE runs

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/getRunStatus.R
- README.md
as `-rem-1` has `cfg$gms$cm_MAgPIE_coupling == "off"`. Not sure why [I implemented this differentiation](https://github.com/pik-piam/modelstats/pull/55/files), it seems to make no sense.
> make sure also -mag-1 shows progress correctly

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/modeltests.R
- README.md
- FYI @fbenke-pik. Once the AMTs are finished the next time and a file was actually uploaded, we need to adjust the filename in remind2 -> https://github.com/pik-piam/remind2/pull/613
> adjust modeltests to SSP2EU -> SSP2 rename

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/promptAndRun.R
- README.md
Somehow, the behavior of `sacct` has changed for `sacct -u laurinko -S 2024-06-01 -s completed -v | head`
old cluster:
```
sacct: Jobs eligible from Sat Jun 01 00:00:00 2024 - Now
```
new cluster:
```
sacct: Jobs COMPLETED in the time window from Sat Jun 01 00:00:00 2024 to Sat Jun 01 00:00:01 2024
```
> fix sacct call in 'rs2 -c'

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/getRunStatus.R
- README.md
- somehow, sometimes some grid files can still be found in the 225a folder
- when doing calculations such as MAGICC7 between the iteration, it might think that conopt stalled while everything is fine.
- don't complain about conopt if latest gdx was written <15 min ago
> don't complain about conopt if latest gdx is written <15 min ago

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/getRunStatus.R
- README.md
- also the error line looks a bit different now, so grep a bit more generally
> let rs2 detect if run was canceled

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/modeltests.R
- README.md
Search for the lastRun in the archive too, not just in output, because it may have been moved in the meantime.
> Search for the lastRun in the archive too, not just in output

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/modeltests.R
- README.md
- man/modeltests.Rd
- modelstats.Rproj
I removed the test mode (activated whit `modeltests(test=TRUE, ...`)) as it was not used anymore.
More important: I replaced the keywords describing the current status of the modeltests with (hopefully) clearer keywords. Using these keyword the status is saved as plain text to `.teststatus`. The keywords now describe what will happen the next time `modeltests()` is called. I replaced:
start -> next:start
end -> next:evaluate
wait -> evaluateRuns() is running or stopped due to an error
In case you agree and approve, please don't forget to update the keywords in your `.teststatus` file!
> Remove test-mode. Change keywords defining the teststatus
